name: weather_app
description: Weather project

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc_pattern: ^3.0.1
  hive: ^2.2.3
  google_sign_in: ^6.1.4
  flutter_facebook_auth: ^5.0.11
  google_fonts: ^4.0.4
  geolocator: ^9.0.2
  flutter_localization: ^0.1.12
  connectivity_plus: ^4.0.1
  sizer: ^2.0.15
  flutter_svg: ^2.0.5
  dio: ^5.3.0
  rxdart: ^0.27.7
  device_info_plus: ^9.0.2
  location: ^5.0.0
  intl: ^0.17.0
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/

